import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, waitFor, fireEvent, within } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import AuditTrail from '../components/AuditTrail'

const MOCK_LOGS = [
  {
    logId: 'LOG-882391',
    timestamp: '2026-04-27T10:15:00Z',
    userId: 'PM_001',
    userName: '李建国',
    actionType: 'UPDATE_THRESHOLD',
    description: '修改「协议偏差率」高风险阈值',
    details: { metric: 'PD_Rate', previousValue: 5.0, newValue: 4.5 },
  },
  {
    logId: 'LOG-776204',
    timestamp: '2026-04-26T15:42:00Z',
    userId: 'CRA_003',
    userName: '张伟',
    actionType: 'CLOSE_ALERT',
    description: '关闭预警 ALT-2026-047',
    details: { alertId: 'ALT-2026-047', previousStatus: 'Open', newStatus: 'Closed' },
  },
  {
    logId: 'LOG-733774',
    timestamp: '2026-04-20T08:30:00Z',
    userId: 'SYSTEM',
    userName: '系统自动',
    actionType: 'CREATE_TASK',
    description: '自动派发工单 TASK-20260420-031',
    details: { taskId: 'TASK-20260420-031', priority: 'Critical', autoGenerated: true },
  },
]

function setup() {
  const c = new QueryClient({ defaultOptions: { queries: { retry: false } } })
  return render(
    <QueryClientProvider client={c}>
      <MemoryRouter>
        <AuditTrail />
      </MemoryRouter>
    </QueryClientProvider>,
  )
}

describe('AuditTrail', () => {
  beforeEach(() => { vi.stubGlobal('fetch', vi.fn()) })

  it('shows loading state', () => {
    (fetch as ReturnType<typeof vi.fn>).mockReturnValue(new Promise(() => {}))
    setup()
    expect(screen.getByText(/加载中/)).toBeInTheDocument()
  })

  it('shows error state on fetch failure', async () => {
    (fetch as ReturnType<typeof vi.fn>).mockRejectedValue(new Error('network'))
    setup()
    await waitFor(() => expect(screen.getByText(/无法加载审计日志/)).toBeInTheDocument())
  })

  it('renders KPI banner counts', async () => {
    (fetch as ReturnType<typeof vi.fn>).mockResolvedValue(new Response(JSON.stringify(MOCK_LOGS), { status: 200 }))
    setup()
    await waitFor(() => expect(screen.getAllByText('阈值变更').length).toBeGreaterThanOrEqual(1))
    expect(screen.getAllByText('预警关闭').length).toBeGreaterThanOrEqual(1)
    expect(screen.getAllByText('工单操作').length).toBeGreaterThanOrEqual(1)
    expect(screen.getAllByText('报告导出').length).toBeGreaterThanOrEqual(1)
  })

  it('renders log rows with user names', async () => {
    (fetch as ReturnType<typeof vi.fn>).mockResolvedValue(new Response(JSON.stringify(MOCK_LOGS), { status: 200 }))
    setup()
    await waitFor(() => expect(screen.getAllByText('李建国').length).toBeGreaterThanOrEqual(1))
    expect(screen.getAllByText('张伟').length).toBeGreaterThanOrEqual(1)
    expect(screen.getAllByText('系统自动').length).toBeGreaterThanOrEqual(1)
  })

  it('renders log IDs', async () => {
    (fetch as ReturnType<typeof vi.fn>).mockResolvedValue(new Response(JSON.stringify(MOCK_LOGS), { status: 200 }))
    setup()
    await waitFor(() => expect(screen.getByText('LOG-882391')).toBeInTheDocument())
    expect(screen.getByText('LOG-776204')).toBeInTheDocument()
  })

  it('shows record count', async () => {
    (fetch as ReturnType<typeof vi.fn>).mockResolvedValue(new Response(JSON.stringify(MOCK_LOGS), { status: 200 }))
    setup()
    await waitFor(() => expect(screen.getByText(/3 \/ 3 条记录/)).toBeInTheDocument())
  })

  it('filters by action type', async () => {
    (fetch as ReturnType<typeof vi.fn>).mockResolvedValue(new Response(JSON.stringify(MOCK_LOGS), { status: 200 }))
    const { container } = setup()
    await waitFor(() => expect(screen.getByLabelText('操作类型')).toBeInTheDocument())
    fireEvent.change(screen.getByLabelText('操作类型'), { target: { value: 'UPDATE_THRESHOLD' } })
    await waitFor(() => expect(screen.getByText(/1 \/ 3 条记录/)).toBeInTheDocument())
    const tbody = container.querySelector('tbody')!
    expect(within(tbody).getByText('李建国')).toBeInTheDocument()
    expect(within(tbody).queryByText('张伟')).not.toBeInTheDocument()
  })

  it('filters by user name', async () => {
    (fetch as ReturnType<typeof vi.fn>).mockResolvedValue(new Response(JSON.stringify(MOCK_LOGS), { status: 200 }))
    const { container } = setup()
    await waitFor(() => expect(screen.getByLabelText('操作人员')).toBeInTheDocument())
    fireEvent.change(screen.getByLabelText('操作人员'), { target: { value: '张伟' } })
    await waitFor(() => expect(screen.getByText(/1 \/ 3 条记录/)).toBeInTheDocument())
    const tbody = container.querySelector('tbody')!
    expect(within(tbody).getByText('张伟')).toBeInTheDocument()
    expect(within(tbody).queryByText('李建国')).not.toBeInTheDocument()
  })

  it('expands row details on click', async () => {
    (fetch as ReturnType<typeof vi.fn>).mockResolvedValue(new Response(JSON.stringify(MOCK_LOGS), { status: 200 }))
    setup()
    await waitFor(() => expect(screen.getByText('修改「协议偏差率」高风险阈值')).toBeInTheDocument())
    fireEvent.click(screen.getByText('修改「协议偏差率」高风险阈值'))
    await waitFor(() => expect(screen.getByText('PD_Rate')).toBeInTheDocument())
  })

  it('shows empty state when no results match filter', async () => {
    (fetch as ReturnType<typeof vi.fn>).mockResolvedValue(new Response(JSON.stringify(MOCK_LOGS), { status: 200 }))
    setup()
    await waitFor(() => expect(screen.getByLabelText('搜索日志')).toBeInTheDocument())
    fireEvent.change(screen.getByLabelText('搜索日志'), { target: { value: 'NOMATCH_XXXXXX' } })
    await waitFor(() => expect(screen.getByText(/未找到匹配的审计记录/)).toBeInTheDocument())
  })
})
